
"""
    visualizations_notebook.ipynb

    Automatically generated by Colaboratory.

    Original file is located at
        https://colab.research.google.com/drive/1N56-XadUMJQ3Zq65bJ3pdEXLaj_Uiojn

    # **Project Plotting - Matplotlib Seaborn, Histograms and Boxplots**

    The most recent ASC23 considered four major systems-based tracks with a view to providing region-focused contributions to inform the global stocktake among them Cities, urban and rural settlements, infrastructure, and transport.

    In this assignment, you will be performing analysis more specifically on transport (vehicles and fuel efficiency).

    The dataset has been provided for you.

    You are tasked to make sense of this data that will later be used for AI purposes.
"""

# from google.colab import drive
# drive.mount('/content/drive')

# prerequisite package imports

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np



"""
    :We'll work with the fuel economy dataset in this workspace.

    Load the dataset and print at least 10 rows

    1.   Load the dataset
    2.   print atleast 10 rows of it

"""

data = pd.read_csv("data/fuel_econ.csv")
print(data.head(10))

"""
    Play Around with Bin size as you create your Histogram

    [Bin size in Matplot Lib](https://www.geeksforgeeks.org/bin-size-in-matplotlib-histogram/)

    **Description**
    The dataset has a number of different statistics that describe fuel efficiency.


    **TO DO**:
    1.   create a _histogram_ that depicts the distribution of carbon Dioxide
    2.   Play  around with different bin width sizes to see what best depicts the data

    Create 2 more histograms based on columns of your choice
"""



# first histogram for co2
carbon = data['co2']

plt.style.use('seaborn-v0_8-colorblind')

plt.title("Distribution of carbon Dioxide")
plt.xlabel('CO2 Emissions (grams per mile)')
plt.ylabel('Frequency')


plt.tight_layout()
plt.hist(carbon,color = "lightsteelblue", bins=100)

plt.show()

plt.savefig('Exported_images/carbon.png')


# second histogram for highway
feScore = data['feScore']
plt.style.use('seaborn-v0_8-colorblind')


plt.title('Distribution of Fuel Efficiency Score')
plt.xlabel('Fuel Efficiency Score')
plt.ylabel('Frequency')


plt.tight_layout()
plt.hist(feScore, bins=10, facecolor = '#f3ce5a', edgecolor='#faecc1', linewidth=0.5)
plt.show()
plt.savefig('Exported_images/fuel_Score.png')



# third histogram for highway
highway = data['highway']
plt.style.use('seaborn-v0_8-colorblind')
plt.xlabel('Highway Fuel Efficiency (MPG)')
plt.ylabel('Frequency')
plt.title('Distribution of Highway Fuel Efficiency')


plt.tight_layout()
plt.hist(highway, bins=30, facecolor = '#f3ce5a', edgecolor='#faecc1', linewidth=0.5)
plt.show()
plt.savefig('Exported_images/Highway_Fuel_Efficiency.png')

"""
    **TO DO: Write Code that will give you the following plot as below:**

    1.   create a heat map of the data
    2.Interpret the data - What story does the visualization tell?

    >

    Finally What Columns would you delete Drop if the target is the ghg score? Justify your Answer
"""


data = pd.read_csv("data/fuel_econ.csv")
data_map = data.drop(['make', 'model', 'VClass', 'drive', 'trans', 'fuelType'], axis=1)
corr = data_map.corr()
sns.color_palette("Spectral", as_cmap=True)
sns.heatmap(corr, cmap="coolwarm")
plt.savefig("Exported_images/seaborn_plot.png")

"""
    2. Interpret the data - What story does the visualization tell?
    i can see a very corralation btn the number of cylinders in a car enginer with the amount of carbondioxde emitted in the atomoshere.
    the more the number of cylinders, the more carbondioxide produced.


    Finally What Columns would you delete Drop if the target is the ghg score? Justify your Answer

    i had to drop these make,model, VClass, drive, trans and uelType columns from the data set, the reason for doing so, was because i neeed only numeric data to work with inorder to create a heat map usign the seaborn library.

"""
